### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by MichaelWGibson** [MichaelWGibson/MazeBot#1]
A general list of software items that need to be developed.

- [ ] State Machine
  - [ ] Start state
  - [ ] Explore state
  - [ ] Collect state
  - [ ] Return state
  - [ ] Finished state
- [ ] Actions
  - [ ] Turn around
  - [ ] Turn right
  - [ ] Turn left
  - [ ] Follow line 
- [ ] Image Processing
  - [x] Adapter for g-streamer cameras
  - [x] Adapter for USB cameras
  - [ ] Line detection
  - [ ] Intersection detection
  - [ ] Ping Pong detection
- [ ] Maze exploration
  - [ ] Build maze graph (intersections as nodes)
  - [ ] Traversal algorithms
  - [ ] Return algorithms
- [x] Drive
  - [x] Build motor controller interface
  - [x] Build drive train
- [x] Development tools
  - [x] Serve camera feed over http
